# Generated by Django 4.2.3 on 2023-07-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_roomfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/post_files/'),
        ),
        migrations.AlterField(
            model_name='roomfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/room_files/'),
        ),
    ]
