# Generated by Django 4.2.3 on 2023-07-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_postfile_file_alter_roomfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage='media/post_files/', upload_to=''),
        ),
    ]
